title = "HackUrCulture"
baseURL = "http://example.org/"
languageCode = "en-us"
theme = "ananke"

[params]
  favicon = ""
  site_logo = ""
  description = "Make History Today!"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hack.jpg"
  recent_posts_number = 20